name: rolls_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cloud_firestore: ^3.5.1
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  email_validator: ^2.1.17
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  flutter_custom_clippers: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  footer: ^0.0.4
  form_field_validator: ^1.1.0
  get: 4.6.5
  google_sign_in: ^5.3.0
  provider: ^6.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  footer: any
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/icon.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/logo/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: fonts/Roboto-Medium.ttf
          weight: 400
  uses-material-design: true
  
        

  

